### ISSUE TITLE
git.gradebot.org not accessible to me

### ISSUE THREAD

**Issue by thejerf** [system-pclub/GCatch#20]
GCatch/GCatch/tools/github.com/aclements/go-z3/st/{gen,types,st_test,cache}.go reference a "git.gradebot.org/zxl381/goconcurrencychecker/tools/github.com/aclements/go-z3/z3", which the general public doesn't seem to be able to get access to.

GCatch builds if I use a replace directive to return that to the original aclements/go-z3 (see https://github.com/thejerf/GCatch/blob/master/docker/Dockerfile ), but I don't know if that will introduce bugs due to not having some sort of bug fix or something.

**Comment by lzhfromustc** [comment]
Hi @thejerf , I have changed the out-of-date dependencies. It should work now
