### ISSUE TITLE
GCatch: default checker (`channel`) doesn't exist

### ISSUE THREAD

**Issue by dgryski** [system-pclub/GCatch#25]
The default checker for GCatch (defined here: https://github.com/system-pclub/GCatch/blob/master/GCatch/cmd/GCatch/main.go#L35 ) does not seem to be listed among the checks in `detect` here: https://github.com/system-pclub/GCatch/blob/master/GCatch/cmd/GCatch/main.go#L177

Similarly, there's no validation that the provided string(s) are valid checker names.

**Comment by dgryski** [comment]
Looks like this patch changed the name but didn't update the flag default: eb66af7cdd8baaff1272a4f228b209fba695e333

**Comment by lzhfromustc** [comment]
Thanks for noticing these problems! I just made a new commit and fixed the problems you mentioned

**Comment by dgryski** [comment]
e3b69d2f1de13dd790dfdb471990a5ec7b093bf1 LGTM.
