### ISSUE TITLE
GCatch: go-cmp causes hang in ComputeDeferMap()

### ISSUE THREAD

**Issue by dgryski** [system-pclub/GCatch#26]
Some of the packages I've tested seem to hang before ever getting to actually run the checker.  I will attempt to produce a minimal test case hopefully showing whatever construct is causing trouble.  (None of the packages that produce this behaviour are public.)

**Comment by dgryski** [comment]
The issue appears to be in the `go-cmp` package, which *is* public source code.

The following test file causes GCatch to hang when processing:

```
package inputs

import (
	"bytes"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestInputs(t *testing.T) {
	testData := []string{
		"input",
	}

	for _, name := range testData {
		var expect []byte
		var w bytes.Buffer

		got := w.String()
		if diff := cmp.Diff(string(expect), got); diff != "" {
			t.Errorf("%s asm mismatch (-want +got):\n%s", name, diff)
		}
	}
}
```

**Comment by songlh** [comment]
@Arcana-2236 can you confirm the problem?

**Comment by lzhfromustc** [comment]
This is an interesting issue. I have never seen ComputeDeferMap() blocks. I will checkout what is happening in go-cmp. Thanks!

**Comment by Arcana-2236** [comment]
Yes,the small test file also causes GCatch to hang when processing on my computer.

**Comment by songlh** [comment]
@lzhfromustc can you figure out the reason and fix the bug?

**Comment by lzhfromustc** [comment]
Thanks for pointing out this problem, and sorry for not replying these days. I was working for a conference

The root cause is that when I copy slices in related code, I copied them in the wrong way. 

Now I use a for loop to copy every element in each slice, and GCatch won't hang on the go-cmp library. #31
