### ISSUE TITLE
Questions about BMOC checker

### ISSUE THREAD

**Issue by dariusf** [system-pclub/GCatch#36]
Hi, I read your paper (really great work!) and have been trying out GCatch. Had a few questions on how channel states are modelled.

1. A deadlock is not detected by the BMOC checker in this program, is this expected (meant to detected by another checker, perhaps)?

```go
package main

func main() {
  a := make(chan int, 1)
  a <- 1
  a <- 1
}
```

```sh
GO111MODULE=off GOPATH=$(pwd)/testdata/toyprogram GCatch -path $GOPATH/src/circularWait -r -checker=BMOC -compile-error -include=circularWait
```

```
Successfully built whole program. Now running checkers
(= G_0_N_0_Order 2)
(>= G_0_N_1_Order 0)
(< G_0_N_1_Order 2)
(= 0 1)
(>= G_0_N_0_Order 0)
(< G_0_N_0_Order 2)
(= G_0_N_1_Order 2)
(> G_0_N_1_Order G_0_N_0_Order)
(< 0 1)
(= 0 1)
-----count_unbuffer_bug: 0 ---buffer_bug: 0
-----count_ch: 1
Now trying to build unchecked packages separately...


Time of main(): seconds 0.1015695
```

I tried to figure out what was happening by printing the queries to Z3. I understand ordering relations, but what do the sync and blocking conditions of `(< 0 1)` and `(= 0 1)` at the end model?

2. I also tried this variation of the toy program included in the repo, but with the channel buffer sizes increased to 1.

```go
package main

func main() {
  a := make(chan int, 1)
  b := make(chan int, 1)
  go func() {
    <- b
    a <- 1
  }()
  <- a
  b <- 1
}

```

```
Successfully built whole program. Now running checkers
(>= G_0_N_0_Order 0)
(< G_0_N_0_Order 5)
(= G_0_N_1_Order 5)
(> G_0_N_1_Order G_0_N_0_Order)
(>= G_0_N_2_Order 0)
(< G_0_N_2_Order 5)
(= G_1_N_0_Order 5)
(>= G_1_N_1_Order 0)
(< G_1_N_1_Order 5)
(> G_1_N_0_Order G_0_N_0_Order)
(ite (< G_0_N_2_Order G_1_N_0_Order) (= Unique_1 (+ 0 1)) (= Unique_1 0))
(ite (< G_1_N_1_Order G_0_N_1_Order) (= Unique_2 (+ 0 1)) (= Unique_2 0))
(= Unique_1 0)
(not false)
(= Unique_2 0)
(not false)
-----count_unbuffer_bug: 0 ---buffer_bug: 0
-----count_ch: 1
(>= G_0_N_0_Order 0)
(< G_0_N_0_Order 5)
(= G_0_N_1_Order 5)
(> G_0_N_1_Order G_0_N_0_Order)
(>= G_0_N_2_Order 0)
(< G_0_N_2_Order 5)
(= G_1_N_0_Order 5)
(>= G_1_N_1_Order 0)
(< G_1_N_1_Order 5)
(> G_1_N_0_Order G_0_N_0_Order)
(ite (< G_1_N_1_Order G_0_N_1_Order) (= Unique_1 (+ 0 1)) (= Unique_1 0))
(ite (< G_0_N_2_Order G_1_N_0_Order) (= Unique_2 (+ 0 1)) (= Unique_2 0))
(= Unique_1 0)
(not false)
(= Unique_2 0)
(not false)
-----count_unbuffer_bug: 0 ---buffer_bug: 0
-----count_ch: 2
Now trying to build unchecked packages separately...


Time of main(): seconds 0.0996304
```

It correctly finds no deadlock, but I'm curious how the `ite` conditions generated model channel states -- I'm guessing `Unique_1`, `Unique_2` are channel sizes at particular program points. In general will there be `ite`s between all pairs of unordered communication events on the same channel?

**Comment by lzhfromustc** [comment]
Thanks for notifying us about this problem!

1. 
In the first example, GCatch should find the bug. Probably our recent updates messed up the blocking operations enumeration or Z3 part, making this bug not found. 

In the second example, GCatch should also find the bug: there is nothing in a and b, so `<- b` and `<- a` should circular wait.

I just opened a new pull request to fix several problems I noticed recently. After this fix, you should be able to detect both bugs. I also added your two examples into testdata/toyprogram/src/bufferCh for convenience.

2.
About the Z3 constraints, sorry my Z3 constants are simply automatically named by the go-z3 package, so even I can't read the printed out log :-( 

However, I can explain how these constants and constraints are generated for buffered channels:
A buffered channel has a Int Z3 constant for its buffer size
Before each send/receive operation of a buffered channel, we generate a Int Z3 constant (naming `nowBuffer` in z3Util.go) for its current buffer. `nowBuffer` is created in a loop, and the algorithm is like below: 
```
nowBuffer := Z3Zero
for OtherOp in all_other_send_and_receive_operations {
  prevBuffer := nowBuffer
  nowBuffer := new_Z3_Int 
  
  // writing if_then_else in Z3 is like below:
  cond = OtherOp_happens_before_CurrentOp
  if OtherOp is send {
	  then = nowBuffer++
  } else if OtherOp is receive {
	  then = nowBuffer--
  } 
  else_ = nowBuffer == prevBuffer
  
  newIfThenElse := cond.IfThenElse(then, else_)
  enforce newIfThenElse
}

return nowBuffer
```

**Comment by dariusf** [comment]
Thanks for your response! I tried both examples again and they work now! Your explanation was also very helpful. What I was missing was that _each_ operation is tested in the way you describe.
